name: test

on:
  push:
  pull_request:

jobs:

  test_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run: |
          cd src/
          CFLAGS="-fsanitize=address -fno-omit-frame-pointer -static-libasan" make -j4

      - name: check binary
        run: |
          cd src/
          ls -al
          ldd ToxProxy
          ls -al ToxProxy
          ls -hal ToxProxy

  test_macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run:  brew install gdb

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run: |
          cd src/
          CFLAGS="-fsanitize=address -fno-omit-frame-pointer" make -j4

      - name: check binary
        run: |
          cd src/
          ls -al
          otool -L ToxProxy || echo "NO ERR"
          ls -al ToxProxy
          ls -hal ToxProxy

  test_macos14arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run: |
          cd src/
          CFLAGS="-fsanitize=address -fno-omit-frame-pointer" make -j4

      - name: check binary
        run: |
          cd src/
          ls -al
          otool -L ToxProxy || echo "NO ERR"
          ls -al ToxProxy
          ls -hal ToxProxy

  test_wine:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          wine libwine-dev libwine wine64 wine64-tools winetricks \
          gcc-mingw-w64-x86-64

      - name: check mingw
        run: dpkg -L gcc-mingw-w64-x86-64

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile binary
        run: |
          cd src/
          ls -al
          export CC=x86_64-w64-mingw32-gcc
          make -j 6 all

      - name: check binary
        run: |
          cd src/
          ls -al
          file ToxProxy.exe
          ls -al ToxProxy.exe
          ls -hal ToxProxy.exe

