name: test

on:
  push:
  pull_request:

jobs:

  test_riscv64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: make script dockcross-linux-riscv64
        run: docker run --rm dockcross/linux-riscv64 > ./dockcross-linux-riscv64; chmod +x ./dockcross-linux-riscv64

      - name: test
        run: ./dockcross-linux-riscv64 bash -c 'ls -al;id;pwd;hostname;uname -a'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: prepare csorma java part
        run:  |
          pwd
          cd src/
          cd csorma/
          javac csorma_generator.java
          java csorma_generator ../sql_tables/

      - name: compile
        run:  |
          ./dockcross-linux-riscv64 bash -c './.cross/cross.sh'

  test_raspi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: make script dockcross-linux-arm64
        run: docker run --rm dockcross/linux-arm64 > ./dockcross-linux-arm64; chmod +x ./dockcross-linux-arm64

      - name: test
        run: ./dockcross-linux-arm64 bash -c 'ls -al;id;pwd;hostname;uname -a'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: prepare csorma java part
        run:  |
          pwd
          cd src/
          cd csorma/
          javac csorma_generator.java
          java csorma_generator ../sql_tables/

      - name: compile
        run:  |
          ./dockcross-linux-arm64 bash -c './.cross/cross.sh'

  test_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          coreutils autoconf libtool pkg-config \
          libsodium-dev libcurl4-gnutls-dev

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run: |
          cd src/
          CFLAGS="-fsanitize=address -fno-omit-frame-pointer -static-libasan" make -j4

      - name: check binary
        run: |
          cd src/
          ls -al
          ldd ToxProxy
          ls -al ToxProxy
          ls -hal ToxProxy

  test_macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run:  brew install libsodium curl

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run: |
          cd src/
          CFLAGS="-fsanitize=address -fno-omit-frame-pointer" make -j4

      - name: check binary
        run: |
          cd src/
          ls -al
          otool -L ToxProxy || echo "NO ERR"
          ls -al ToxProxy
          ls -hal ToxProxy

  test_macos14arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run:  brew install libsodium curl

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run: |
          cd src/
          CFLAGS="-fsanitize=address -fno-omit-frame-pointer" make -j4

      - name: check binary
        run: |
          cd src/
          ls -al
          otool -L ToxProxy || echo "NO ERR"
          ls -al ToxProxy
          ls -hal ToxProxy

  test_wine:
    runs-on: ubuntu-22.04
    if: ${{ true }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          wine libwine-dev libwine wine64 wine64-tools winetricks \
          make wget git coreutils autoconf \
          libtool pkg-config nano vim gcc-mingw-w64-x86-64 \
          gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 \
          mingw-w64-tools pkg-config-mingw-w64-x86-64 win-iconv-mingw-w64-dev \
          mingw-w64-x86-64-dev

      - name: check mingw
        run: dpkg -L gcc-mingw-w64-x86-64

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: deps
        run: |
            C_="$(pwd)"
            mkdir -p "$C_"/workspace2/build/
            mkdir -p "$C_"/workspace2/build/inst/
            LIBCURL_VERSION="7.80.0"; LIBCURL_FILENAME="curl-7.86.0.tar.gz" ;  wget "https://github.com/curl/curl/releases/download/curl-7_86_0/curl-7.86.0.tar.gz" -O libcurl.tgz
            SODIUM_VERSION=1.0.19 ; wget "https://github.com/jedisct1/libsodium/releases/download/${SODIUM_VERSION}-RELEASE/libsodium-${SODIUM_VERSION}.tar.gz" -O libsodium.tgz
            OPENSSL_VERSION=1.1.1l ; wget "https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz" -O openssl.tgz
            tar -xzvf libcurl.tgz
            tar -xzvf libsodium.tgz
            tar -xzvf openssl.tgz

      - name: compile libsodium
        run: |
            C_="$(pwd)"
            cd "$C_"/libsodium-stable/ && \
            ARCH="x86_64" && \
            export ARCH && \
            ./configure  \
                      --prefix="$C_""/workspace2/build/inst/" \
                      --host=${ARCH}-w64-mingw32 && \
            make -j$(nproc) && \
            make install

      - name: compile openssl
        run: |
            C_="$(pwd)"
            cd ./openssl-1.1.1l/ && \
            ARCH="x86_64" && \
            export ARCH && \
            ./Configure  \
                      --prefix="$C_""/workspace2/build/inst/" \
                      --cross-compile-prefix=${ARCH}-w64-mingw32- \
                      mingw64 && \
            make -j$(nproc) && \
            make install


      - name: compile libcurl
        run: |
            C_="$(pwd)"
            cd ./curl-7.86.0/ && \
            ARCH="x86_64" && \
            export ARCH && \
            ./configure  \
                      --prefix="$C_""/workspace2/build/inst/" \
                      --with-openssl="$C_""/workspace2/build/inst/" \
                      --host=${ARCH}-w64-mingw32 \
                      --disable-ftp \
                      --disable-file \
                      --disable-ldap \
                      --disable-ldaps \
                      --disable-rtsp \
                      --disable-telnet \
                      --disable-tftp \
                      --disable-pop3 \
                      --disable-imap \
                      --disable-smb \
                      --disable-smtp \
                      --disable-gopher \
                      --disable-mqtt \
                      --disable-manual \
                      --disable-websockets \
                      --with-ca-fallback \
                      --enable-static \
                      --disable-shared && \
            make -j$(nproc) && \
            make install

      - name: compile binary
        run: |
            ls -al ./workspace2/build/inst/
            echo "============"
            ls -al ./workspace2/build/inst/lib/

      - name: compile binary
        run: |
            C_="$(pwd)"
            export _INST2_="$C_""/workspace2/build/inst/"
            export LD_LIBRARY_PATH="$_INST2_"/lib/
            export PKG_CONFIG_PATH="$_INST2_"/lib/pkgconfig
            export CFLAGS=" -fPIC -std=gnu99 -I$_INST2_/include/ -L/usr/x86_64-w64-mingw32/lib/ -L$_INST2_/lib -fstack-protector-all -D_FORTIFY_SOURCE=2 "
            cd src/
            ls -al
            export CC=x86_64-w64-mingw32-gcc
            make -j

      - name: check binary
        run: |
          cd src/
          ls -al
          file ToxProxy.exe
          ls -al ToxProxy.exe
          ls -hal ToxProxy.exe

