name: test

on:
  push:
  pull_request:

jobs:

  test_raspi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: make script dockcross-linux-arm64
        run: docker run --rm dockcross/linux-arm64 > ./dockcross-linux-arm64; chmod +x ./dockcross-linux-arm64

      - name: test
        run: ./dockcross-linux-arm64 bash -c 'ls -al;id;pwd;hostname;uname -a'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: java-version
        run: java -version

      - name: compile
        run:  |
          ./dockcross-linux-arm64 bash -c 'git clone https://github.com/jedisct1/libsodium;cd libsodium/; git checkout 1.0.19; ./autogen.sh; ./configure --host="aarch64-unknown-linux-gnu" --disable-shared; make -j30;make install'

      #- name: compile
      #  run:  |
      #    ./dockcross-linux-arm64 bash -c 'cd src/ ; make -j4'

